services:
  audiMeta:
    container_name: audiMeta
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4005:4005"
    environment:
      - DATABASE_URL="postgresql://domain.tld:5432/postgres"